// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT2wv6jK-whaCfxYrPnpmuoUCcI8t_yvs',
    appId: '1:568687133719:web:0de03e1cd2e58ee139c852',
    messagingSenderId: '568687133719',
    projectId: 'e-comm-firebase-9c2e8',
    authDomain: 'e-comm-firebase-9c2e8.firebaseapp.com',
    storageBucket: 'e-comm-firebase-9c2e8.appspot.com',
    measurementId: 'G-XLKF9RSZV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwNQ2SglIlrKCcOS-D1Q_NuJcVs0YvWfA',
    appId: '1:568687133719:android:054131098e66c34039c852',
    messagingSenderId: '568687133719',
    projectId: 'e-comm-firebase-9c2e8',
    storageBucket: 'e-comm-firebase-9c2e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfHm6RgrVfTYT_o6tT9f4Ah8Yp7LCWVI',
    appId: '1:568687133719:ios:00480ec64a42726a39c852',
    messagingSenderId: '568687133719',
    projectId: 'e-comm-firebase-9c2e8',
    storageBucket: 'e-comm-firebase-9c2e8.appspot.com',
    androidClientId: '568687133719-39f2gbprotsptgbfoio00af1tgav2bgk.apps.googleusercontent.com',
    iosClientId: '568687133719-220gngaoo1r9f830992u2q4g09qmsl8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.taska',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPfHm6RgrVfTYT_o6tT9f4Ah8Yp7LCWVI',
    appId: '1:568687133719:ios:00480ec64a42726a39c852',
    messagingSenderId: '568687133719',
    projectId: 'e-comm-firebase-9c2e8',
    storageBucket: 'e-comm-firebase-9c2e8.appspot.com',
    androidClientId: '568687133719-39f2gbprotsptgbfoio00af1tgav2bgk.apps.googleusercontent.com',
    iosClientId: '568687133719-220gngaoo1r9f830992u2q4g09qmsl8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.taska',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYaYYiy0dUU8hiXfFSraciUpbMdeK3aWI',
    appId: '1:568687133719:web:4e6ede1c91ab668d39c852',
    messagingSenderId: '568687133719',
    projectId: 'e-comm-firebase-9c2e8',
    authDomain: 'e-comm-firebase-9c2e8.firebaseapp.com',
    storageBucket: 'e-comm-firebase-9c2e8.appspot.com',
    measurementId: 'G-MQL3EP1884',
  );
}
